// Generated by CoffeeScript 1.7.1

/*
  backbone-sql.js 0.5.7
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-sql
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {
  var SqlBackboneAdapter, inflection, util, _;

  util = require('util');

  inflection = require('inflection');

  _ = require('underscore');

  module.exports = SqlBackboneAdapter = (function() {
    function SqlBackboneAdapter() {}

    SqlBackboneAdapter.nativeToAttributes = function(json, schema) {
      var key;
      for (key in json) {
        if (json[key] !== null && schema.fields[key] && schema.fields[key].type === 'Boolean') {
          json[key] = !!json[key];
        }
      }
      return json;
    };

    return SqlBackboneAdapter;

  })();

}).call(this);
