// Generated by CoffeeScript 1.6.3
(function() {
  var SqlBackboneAdapter, inflection, util, _;

  util = require('util');

  inflection = require('inflection');

  _ = require('underscore');

  module.exports = SqlBackboneAdapter = (function() {
    function SqlBackboneAdapter() {}

    SqlBackboneAdapter.nativeToAttributes = function(json, schema) {
      var key;
      for (key in json) {
        if (json[key] !== null && schema.fields[key] && schema.fields[key].type === 'Boolean') {
          json[key] = !!json[key];
        }
      }
      return json;
    };

    return SqlBackboneAdapter;

  })();

}).call(this);
