// Generated by CoffeeScript 1.7.1

/*
  backbone-sql.js 0.5.5
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-sql
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
 */

(function() {
  module.exports = {
    sync: require('./sync')
  };

}).call(this);
