// Generated by CoffeeScript 1.6.3
/*
  backbone-sql.js 0.5.2
  Copyright (c) 2013 Vidigami - https://github.com/vidigami/backbone-sql
  License: MIT (http://www.opensource.org/licenses/mit-license.php)
*/


(function() {
  module.exports = {
    sync: require('./sync')
  };

}).call(this);
