// Generated by CoffeeScript 1.9.3
(function() {
  var DatabaseURL, PROTOCOLS, Utils;

  DatabaseURL = require('backbone-orm').DatabaseURL;

  PROTOCOLS = {
    'mysql:': 'mysql',
    'mysql2:': 'mysql',
    'postgres:': 'postgres',
    'pg:': 'postgres',
    'sqlite:': 'sqlite3',
    'sqlite3:': 'sqlite3'
  };

  module.exports = Utils = (function() {
    function Utils() {}

    Utils.protocolType = function(url) {
      if (!url.protocol) {
        url = new DatabaseURL(url);
      }
      return PROTOCOLS[url.protocol];
    };

    return Utils;

  })();

}).call(this);
